In [1]:
# learning notebook

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/datasets/prasertk/top-japanese-game-publishers-stock-price/japanese game publishers stock price 2000-2023.csv

In [2]:
df = pd.read_csv(r'/kaggle/input/datasets/prasertk/top-japanese-game-publishers-stock-price/japanese game publishers stock price 2000-2023.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34826 entries, 0 to 34825
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       34826 non-null  object
 1   Symbol     34826 non-null  object
 2   Company    34826 non-null  object
 3   High       34826 non-null  float64
 4   Low        34826 non-null  float64
 5   Open       34826 non-null  float64
 6   Close      34826 non-null  float64
 7   Volume     34826 non-null  int64
 8   Adj Close  34826 non-null  float64
dtypes: float64(5), int64(1), object(3)
memory usage: 2.4+ MB

In [3]:
df['Date'] = pd.to_datetime(df['Date'])

# reset index after sort
df = df.sort_values(['Company', 'Date']).reset_index(drop=True)

In [4]:
# Verify companies have own row counts
print(df['Company'].value_counts())

Company
konami         5957
sony           5910
capcom         5743
nintendo       5743
square enix    5742
sega           5731
Name: count, dtype: int64

In [5]:
df.isna().sum()

Date         0
Symbol       0
Company      0
High         0
Low          0
Open         0
Close        0
Volume       0
Adj Close    0
dtype: int64

In [6]:
df.describe()

,Date,High,Low,Open,Close,Volume,Adj Close
count,34826,34826.000000,34826.000000,34826.000000,34826.000000,3.482600e+04,34826.000000
mean,2012-03-31 02:04:44.890598912,3071.876556,2998.618360,3035.928167,3035.417772,3.143449e+06,2603.655697
min,2000-01-04 00:00:00,221.250000,214.250000,214.750000,220.250000,0.000000e+00,154.681320
25%,2006-05-02 00:00:00,1337.000000,1304.000000,1320.000000,1320.125000,5.630000e+05,1051.238647
50%,2012-03-27 00:00:00,2414.250000,2351.750000,2385.000000,2384.000000,1.207600e+06,1886.595093
75%,2018-02-09 00:00:00,4120.000000,4040.000000,4080.000000,4080.000000,3.261900e+06,3433.071777
max,2024-01-05 00:00:00,16950.000000,16250.000000,16850.000000,16300.000000,2.613730e+08,15318.176758
std,NaN,2454.768507,2398.815924,2427.822637,2427.715711,6.500641e+06,2317.810923

In [7]:

# Step 5 — Check for duplicate per company
dupes = df.groupby(['Company', 'Date']).size()
print(dupes[dupes > 1])  # Should be empty

Series([], dtype: int64)

In [8]:
# use loc to search through index for zero volume
# use np.where for cleaner format : where(col < x, true, false)

df['Z_Volume'] = np.where(df['Volume'] < 1, 1, 0)

In [9]:
df.head()

,Date,Symbol,Company,High,Low,Open,Close,Volume,Adj Close,Z_Volume
0,2001-01-04,9697.T,capcom,987.5,967.5,967.5,982.5,142000,675.148560,0
1,2001-01-05,9697.T,capcom,1025.0,995.0,1000.0,1020.0,488800,700.917603,0
2,2001-01-08,9697.T,capcom,1020.0,1020.0,1020.0,1020.0,0,700.917603,1
3,2001-01-09,9697.T,capcom,1045.0,987.5,1030.0,1002.5,1161200,688.892151,0
4,2001-01-10,9697.T,capcom,1020.0,975.0,990.0,1020.0,290400,700.917603,0